AnimalShelter/Models/Animal.cs
namespace AnimalShelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Name { get; set; }
    public string DateOfAdmission { get; set; }
    public string TypeOfAnimal { get; set; }
    public string Breed { get; set; }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }
    public AnimalShelterContext(DbContextOptions options)
      : base(options)
    {

    }
  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Animal> model = _db.Animals
        .OrderBy(animal => animal.DateOfAdmission)
        .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }
    public ActionResult SearchDetails(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }
    public ActionResult Search(string searchTerm, string searchby)
    {

      List<Animal> animalList = new List<Animal>();
      if(searchby.Contains("Breed"))
      {
        animalList = _db.Animals.Where(animal => animal.Breed.Contains(searchTerm)).ToList();

      }
      else if(searchby.Contains("Type"))
      {
        animalList = _db.Animals.Where(animal => animal.TypeOfAnimal.Contains(searchTerm)).ToList();
        
        
      }
      else if(searchby.Contains("Name")) {
        animalList = _db.Animals.Where(animal => animal.Name.Contains(searchTerm)).ToList();
        
      }
      
      return View(animalList);
    }
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
  public class HomeController : Controller 
  {
    // [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal
<h3>Add a new animal</h3>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.DateOfAdmission)
  @Html.EditorFor(model => model.DateOfAdmission, new { htmlAttributes = new { @class = "form-control", type ="date"} })
  <br>
  @Html.LabelFor(model => model.TypeOfAnimal)
  @Html.TextBoxFor(model => model.TypeOfAnimal)
  <br>
  @Html.LabelFor(model => model.Breed)
  @Html.TextBoxFor(model => model.Breed)
  <br>
  <input type="submit" value="Add new animal" />
}
<p>@Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details:</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
<h3>
<h4>@Html.DisplayNameFor(model => model.TypeOfAnimal): @Html.DisplayFor(model => model.TypeOfAnimal)
<h4>
<h4>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)
<h4>
<p>@Html.DisplayNameFor(model => model.DateOfAdmission): @Html.DisplayFor(model => model.DateOfAdmission)
<p>

<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}
@using AnimalShelter.Models;
@* @model ToDoList.Models.Item *@

<h1>Animals</h1>
@if (Model.Count == 0)
{
  <h2>There are no animals yet.</h2>
}
<ul>
  @foreach(Animal animal in Model)
  {
    <li>@Html.ActionLink($"{animal.Name}", "Details", new {id = animal.AnimalId})</li>
  }
</ul>


<p>@Html.ActionLink("Add new Animal", "Create")</p>

@* @model AnimalShelter.Models.Animal; *@
@using (Html.BeginForm("Search", "Animals", method: FormMethod.Get))
{
  <select name="searchby" id="searchby">
    <option>Breed</option>
    <option>Type</option>
    <option>Name</option>
  </select>
  

  @* @Html.TextBoxFor(model => Model.Name)  *@
  <input type="text" name="searchTerm"/>
  
  <input type="submit" value="Search"/>
}

AnimalShelter/Views/Animals/Search.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;

<h1>Search</h1>

@foreach(Animal animal in Model)
{
  <li>@Html.ActionLink($"{animal.Name}", "SearchDetails", new {id = animal.AnimalId})</li> 
} 

<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/SearchDetails.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details:</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
<h3>
<h4>@Html.DisplayNameFor(model => model.TypeOfAnimal): @Html.DisplayFor(model => model.TypeOfAnimal)
<h4>
<h4>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)
<h4>
<p>@Html.DisplayNameFor(model => model.DateOfAdmission): @Html.DisplayFor(model => model.DateOfAdmission)
<p>

<p>@Html.ActionLink("Back to list", "Index")</p>


<a href="javascript:void(0);" onclick="history.go(-1)">Back to Search Results</a>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<h1>CHOW CHOW POUND</h1>
<p>@Html.ActionLink("Check out our animals", "Index", "Animals")</p>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Animal Shelter</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body class="d-flex align-items-center justify-content-center p-4">
  <div class="jumbotron p-4 text-center shadow-lg bg-white " id="jumb">
    @RenderBody()
    @* @await Html.PartialAsync("Footer") *@
  </div>
</body>

</html>